# See https://cloud.google.com/cloud-build/docs/build-config

# this must be specified in seconds. If omitted, defaults to 600s (10 mins)
# the timeout was increased because some images might take longer to build (e.g.: sample-apiserver, pets/redis-installer)
timeout: 5400s
# this prevents errors if you don't use both _GIT_TAG and _PULL_BASE_REF,
# or any new substitutions added in the future.
options:
  substitution_option: ALLOW_LOOSE
steps:
- name: install envsub
  args:
  - | 
    if [ ! "$WITHOUT_ENVSUBST" ] && [ ! -x "$(command -v envsubst)" ]; then
      sudo apt-get update && sudo apt-get -y install gettext-base
    fi
- name: unit
  env:
  - 'T=unit'
  args: ['cd ./admission-webhook && ./run-ci.sh']
- name: integration
  env:
  - 'T=integration'
  args: ['cd ./admission-webhook && ./run-ci.sh']
- name: deploy-method-download
  env:
  - 'T=integration'
  - 'DEPLOY_METHOD=download'
  args: ['cd ./admission-webhook && ./run-ci.sh']
- name: tolerate-control-plane
  env:
  - 'T=integration'
  - 'NUM_NODES=0'
  - 'EXTRA_GMSA_DEPLOY_ARGS=--tolerate-master'
  args: [ 'cd ./admission-webhook && ./run-ci.sh' ]
- name: dry-run-deploy
  env:
    - 'T=dry_run_deploy'
  args: [ 'cd ./admission-webhook && ./run-ci.sh' ]
- name: without-envsubst
  env:
    - 'T=integration'
    - 'WITHOUT_ENVSUBST=1'
  args: [ 'cd ./admission-webhook && ./run-ci.sh' ]
- name: without-envsubst-tolerations
  env:
  - 'T=integration'
  - 'NUM_NODES=0'
  - 'WITHOUT_ENVSUBST=1'
  - 'EXTRA_GMSA_DEPLOY_ARGS=--tolerate-master'
  args: [ 'cd ./admission-webhook && ./run-ci.sh' ]
- name: 'push'
  entrypoint: make
  env:
  - TAG=$_GIT_TAG
  - BASE_REF=$_PULL_BASE_REF
  args: ["image_push"]
substitutions:
  # _GIT_TAG will be filled with a git-based tag for the image, of the form vYYYYMMDD-hash, and
  # can be used as a substitution
  _GIT_TAG: '12345'
  # _PULL_BASE_REF will contain the ref that was pushed to trigger this build -
  # a branch like 'master' or 'release-0.2', or a tag like 'v0.2'.
  _PULL_BASE_REF: 'master'