apiVersion: v1
entries:
  gmsa:
  - apiVersion: v2
    appVersion: 0.6.1
    created: "2023-08-09T10:58:23.755451-06:00"
    description: Windows GMSA Configuration
    digest: c13d93a6ff7ff7f3219acd3b85ea085d1294f6d10a63a9d51d5c86d01dc80cb2
    keywords:
    - Windows
    - Windows GMSA
    - GMSA
    - Active Directory
    name: gmsa
    sources:
    - https://github.com/kubernetes-sigs/windows-gmsa
    type: application
    urls:
    - https://raw.githubusercontent.com/kubernetes-sigs/windows-gmsa/master/charts/gmsa-0.7.1.tgz
    version: 0.7.1
  - apiVersion: v2
    appVersion: 0.6.0
    created: "2023-08-09T10:58:23.755188-06:00"
    description: Windows GMSA Configuration
    digest: 9b5fc25c235bac92af9ab0d960de8641b3a638ec8904326f2640f468e113b4ec
    keywords:
    - Windows
    - Windows GMSA
    - GMSA
    - Active Directory
    name: gmsa
    sources:
    - https://github.com/kubernetes-sigs/windows-gmsa
    type: application
    urls:
    - https://raw.githubusercontent.com/kubernetes-sigs/windows-gmsa/master/charts/gmsa-0.7.0.tgz
    version: 0.7.0
  - apiVersion: v2
    appVersion: 0.4.0
    created: "2023-08-09T10:58:23.754936-06:00"
    description: Windows GMSA Configuration
    digest: b637cee6f623598cca5611c3854514875ce1363d915ad8cdd4dabd8d96483546
    keywords:
    - Windows
    - Windows GMSA
    - GMSA
    - Active Directory
    name: gmsa
    sources:
    - https://github.com/kubernetes-sigs/windows-gmsa
    type: application
    urls:
    - https://raw.githubusercontent.com/kubernetes-sigs/windows-gmsa/master/charts/gmsa-0.6.0.tgz
    version: 0.6.0
  - apiVersion: v2
    appVersion: 0.4.0
    created: "2023-08-09T10:58:23.754618-06:00"
    description: Windows GMSA Configuration
    digest: 19003bcc3f5af484afd5a9ad0c833a861420daf7e50964563ecaf92e4a1dc35c
    keywords:
    - Windows
    - Windows GMSA
    - GMSA
    - Active Directory
    name: gmsa
    sources:
    - https://github.com/kubernetes-sigs/windows-gmsa
    type: application
    urls:
    - https://raw.githubusercontent.com/kubernetes-sigs/windows-gmsa/master/charts/gmsa-0.5.0.tgz
    version: 0.5.0
  - apiVersion: v2
    appVersion: 0.4.0
    created: "2023-08-09T10:58:23.754313-06:00"
    description: Windows GMSA Configuration
    digest: 1f6b8bbfe6af4088f80d08d3065094ab1504054526bea6e4477459fb738f504b
    keywords:
    - Windows
    - Windows GMSA
    - GMSA
    - Active Directory
    name: gmsa
    sources:
    - https://github.com/kubernetes-sigs/windows-gmsa
    type: application
    urls:
    - https://raw.githubusercontent.com/kubernetes-sigs/windows-gmsa/master/charts/gmsa-0.4.4.tgz
    version: 0.4.4
  - apiVersion: v2
    appVersion: 0.4.0
    created: "2023-08-09T10:58:23.754052-06:00"
    description: Windows GMSA Configuration
    digest: 6ae2ac87141c8e3ac598611153635b0dd6619634ddc27b27b9c1a8717a511d8a
    keywords:
    - Windows
    - Windows GMSA
    - GMSA
    - Active Directory
    name: gmsa
    sources:
    - https://github.com/kubernetes-sigs/windows-gmsa
    type: application
    urls:
    - https://raw.githubusercontent.com/kubernetes-sigs/windows-gmsa/master/charts/gmsa-0.4.3.tgz
    version: 0.4.3
  - apiVersion: v2
    appVersion: 0.4.0
    created: "2023-08-09T10:58:23.753799-06:00"
    description: Windows GMSA Configuration
    digest: 399a4d03dfc08ac4cd811106ab55d525845ca715f0edbdcfcafcfa02cceaf108
    keywords:
    - Windows
    - Windows GMSA
    - GMSA
    - Active Directory
    name: gmsa
    sources:
    - https://github.com/kubernetes-sigs/windows-gmsa
    type: application
    urls:
    - https://raw.githubusercontent.com/kubernetes-sigs/windows-gmsa/master/charts/gmsa-0.4.2.tgz
    version: 0.4.2
  - apiVersion: v2
    appVersion: 0.4.0
    created: "2023-08-09T10:58:23.753536-06:00"
    description: Windows GMSA Configuration
    digest: 0709c8666554bf7b521c003d33f6198dafe03bf883161e132e929dac478bda45
    keywords:
    - Windows
    - Windows GMSA
    - GMSA
    - Active Directory
    name: gmsa
    sources:
    - https://github.com/kubernetes-sigs/windows-gmsa
    type: application
    urls:
    - https://raw.githubusercontent.com/kubernetes-sigs/windows-gmsa/master/charts/gmsa-0.4.1.tgz
    version: 0.4.1
  - apiVersion: v2
    appVersion: 0.4.0
    created: "2023-08-09T10:58:23.753138-06:00"
    description: Windows GMSA Configuration
    digest: 7f29d22ba85d90a18e5b9c4e1a7d9ba1149d5827a2ca37b9a6fe1966e3598767
    keywords:
    - Windows
    - Windows GMSA
    - GMSA
    - Active Directory
    name: gmsa
    sources:
    - https://github.com/kubernetes-sigs/windows-gmsa
    type: application
    urls:
    - https://raw.githubusercontent.com/kubernetes-sigs/windows-gmsa/master/charts/gmsa-0.4.0.tgz
    version: 0.4.0
generated: "2023-08-09T10:58:23.752673-06:00"
