{{- if .Values.certificates.certManager.enabled -}}
{{ template "cert-manager.apiversion" . }}
kind: Certificate
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
  labels: {{ include "gmsa.chartref" . | nindent 4 }}
spec:
  dnsNames:
    - {{ .Release.Name }}.{{ .Release.Namespace }}.svc
    - {{ .Release.Name }}.{{ .Release.Namespace }}.svc.cluster.local
  issuerRef:
    kind: Issuer
    name: {{ .Release.Name }}
  secretName: {{ .Values.certificates.secretName }}
  {{- if .Values.certificates.certReload.enabled }}
  privateKey:
    rotationPolicy: Always
  {{- end }}
---
{{ template "cert-manager.apiversion" . }}
kind: Issuer
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
  labels: {{ include "gmsa.chartref" . | nindent 4 }}
spec:
  ca:
    secretName: {{ .Release.Name }}-root-ca
---
{{ template "cert-manager.apiversion" . }}
kind: ClusterIssuer
metadata:
  name: {{ .Release.Name }}-ca
spec:
  selfSigned: {}
---
{{ template "cert-manager.apiversion" . }}
kind: Certificate
metadata:
  name: {{ .Release.Name }}-ca
  namespace: {{ .Release.Namespace }}
spec:
  isCA: true
  commonName: {{ .Release.Name }}-ca
  secretName: {{ .Release.Name }}-root-ca
  issuerRef:
    name: {{ .Release.Name }}-ca
    kind: ClusterIssuer
    group: cert-manager.io
---
{{- end -}}