## a simple deployment with several containers: 2 with their own GMSA, and 1 without it, plus a pod-level cred spec

apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: {{ .TestName }}
  name: {{ .TestName }}
  namespace: {{ .Namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .TestName }}
  template:
    metadata:
      labels:
        app: {{ .TestName }}
    spec:
      serviceAccountName: {{ .ServiceAccountName }}
      securityContext:
        windowsOptions:
          gmsaCredentialSpecName: {{ index .CredSpecNames 1 }}
      containers:
      - image: k8s.gcr.io/pause
        name: nginx0
        securityContext:
          windowsOptions:
            gmsaCredentialSpecName: {{ index .CredSpecNames 0 }}
      - image: k8s.gcr.io/pause
        name: nginx1
      - image: k8s.gcr.io/pause
        name: nginx2
        securityContext:
          windowsOptions:
            gmsaCredentialSpecName: {{ index .CredSpecNames 2 }}
{{- range $line := .ExtraSpecLines }}
      {{ $line }}
{{- end }}
