## a simple deployment with a container-level cred spec GMSA's *contents* already set (and not its name)

apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: {{ .TestName }}
  name: {{ .TestName }}
  namespace: {{ .Namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .TestName }}
  template:
    metadata:
      labels:
        app: {{ .TestName }}
    spec:
      serviceAccountName: {{ .ServiceAccountName }}
      containers:
      - image: k8s.gcr.io/pause
        name: nginx
        securityContext:
          windowsOptions:
            gmsaCredentialSpec: '{"ActiveDirectoryConfig":{"GroupManagedServiceAccounts":[{"Name":"WebApplication0","Scope":"CONTOSO"},{"Name":"WebApplication0","Scope":"contoso.com"}]},"CmsPlugins":["ActiveDirectory"],"DomainJoinConfig":{"DnsName":"contoso.com","DnsTreeName":"contoso.com","Guid":"244818ae-87ca-4fcd-92ec-e79e5252348a","MachineAccountName":"WebApplication0","NetBiosName":"CONTOSO","Sid":"S-1-5-21-2126729477-2524075714-3094792973"}}'
{{- range $line := .ExtraSpecLines }}
      {{ $line }}
{{- end }}
