## a simple deployment with a fully specified GMSA cred spec (ie both its name and contents);
## but where the specified contents don't match the name

apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: {{ .TestName }}
  name: {{ .TestName }}
  namespace: {{ .Namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .TestName }}
  template:
    metadata:
      labels:
        app: {{ .TestName }}
    spec:
      serviceAccountName: {{ .ServiceAccountName }}
      securityContext:
        windowsOptions:
          gmsaCredentialSpecName: {{ index .CredSpecNames 0 }}
          gmsaCredentialSpec: '{"ActiveDirectoryConfig":{"GroupManagedServiceAccounts":[{"Name":"WebApplication1","Scope":"CONTOSO"},{"Name":"WebApplication1","Scope":"contoso.com"}]},"CmsPlugins":["ActiveDirectory"],"DomainJoinConfig":{"DnsName":"contoso.com","DnsTreeName":"contoso.com","Guid":"244818ae-87ca-4fcd-92ec-e79e5252348a","MachineAccountName":"WebApplication1","NetBiosName":"CONTOSO","Sid":"S-1-5-21-2126729477-2524175714-3194792973"}}'
      containers:
      - image: k8s.gcr.io/pause
        name: nginx
{{- range $line := .ExtraSpecLines }}
      {{ $line }}
{{- end }}
