## a simple deployment with a fully specified GMSA cred spec (ie both its name and contents)

apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: {{ .TestName }}
  name: {{ .TestName }}
  namespace: {{ .Namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .TestName }}
  template:
    metadata:
      labels:
        app: {{ .TestName }}
    spec:
      serviceAccountName: {{ .ServiceAccountName }}
      securityContext:
        windowsOptions:
          gmsaCredentialSpecName: {{ index .CredSpecNames 0 }}
          gmsaCredentialSpec: '{"CmsPlugins":["ActiveDirectory"],  "ActiveDirectoryConfig":{"GroupManagedServiceAccounts":[{"Name":"WebApplication0","Scope":"CONTOSO"},{"Name":"WebApplication0","Scope":"contoso.com"}]},"DomainJoinConfig":{"Sid":"S-1-5-21-2126729477-2524075714-3094792973",  "DnsName":"contoso.com","DnsTreeName":"contoso.com","Guid":"244818ae-87ca-4fcd-92ec-e79e5252348a","MachineAccountName":"WebApplication0","NetBiosName":"CONTOSO"}}'
      containers:
      - image: k8s.gcr.io/pause
        name: nginx
{{- range $line := .ExtraSpecLines }}
      {{ $line }}
{{- end }}
