name: build

on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master

jobs:
  unit:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v2
    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17
    - id: test-runner
      uses: ./.github/actions/tests
      env:
        T: unit
  integration:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v2
    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17
    - id: test-runner
      uses: ./.github/actions/tests
      env:
        T: integration
  deploy-method-download:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v2
    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17
    - id: test-runner
      uses: ./.github/actions/tests
      env:
        T: integration
        DEPLOY_METHOD: download
  tolerate-control-plane:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v2
    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17
    - id: test-runner
      uses: ./.github/actions/tests
      env:
        T: integration
        NUM_NODES: 0
        EXTRA_GMSA_DEPLOY_ARGS: --tolerate-master
  dry-run-deploy:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v2
    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17
    - id: test-runner
      uses: ./.github/actions/tests
      env:
        T: dry_run_deploy
  without-envsubst:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v2
    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17
    - id: test-runner
      uses: ./.github/actions/tests
      env:
        T: integration
        WITHOUT_ENVSUBST: 1
  without-envsubst-tolerations:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v2
    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17
    - id: test-runner
      uses: ./.github/actions/tests
      env:
        T: integration
        NUM_NODES: 0
        WITHOUT_ENVSUBST: 1
        EXTRA_GMSA_DEPLOY_ARGS: --tolerate-master
  chart-integration:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v2
    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17
    - id: test-runner
      uses: ./.github/actions/tests
      env:
        T: integration
        DEPLOY_METHOD: chart
